name: creativeagent
metadata:
  template: creativeagent@0.0.1-beta
hooks:
  postprovision:
    posix:
      shell: sh
      continueOnError: false
      interactive: true
      run: infra/hooks/postprovision.sh
    windows:
      shell: pwsh
      continueOnError: false
      interactive: true
      run: infra/hooks/postprovision.ps1
  postdeploy:
#      windows:
#        shell: pwsh
#        run: azd env set REACT_APP_API_BASE_URL $env:SERVICE_API_ENDPOINT_URL
#      posix:
#        shell: sh
#        run: azd env set REACT_APP_API_BASE_URL ${SERVICE_API_ENDPOINT_URL}
infra:
    provider: "bicep"

pipeline:
  variables:
    - AZURE_OPENAI_ENDPOINT
    - AZURE_OPENAI_API_VERSION
    - AZURE_OPENAI_4_EVAL_DEPLOYMENT_NAME
    - AZURE_OPENAI_DEPLOYMENT_NAME
    - AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME
    - AZURE_SEARCH_ENDPOINT
    - AZURE_SEARCH_INDEX_NAME
    - BING_SEARCH_ENDPOINT
  secrets:
    - BING_SEARCH_KEY